auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096 # Default GRPC port

common:
  path_prefix: /loki # Directory for WAL, BoltDB shipper, etc.
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1 # Suitable for single instance
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2022-01-01 # Start date for this schema
      store: boltdb-shipper
      object_store: filesystem
      schema: v13 # A common and stable schema version
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
  filesystem: # This defines the 'filesystem' object_store used by schema_config and boltdb_shipper
    directory: /loki/chunks # Chunks will be stored here

compactor:
  working_directory: /loki/compactor
  delete_request_store: filesystem
  compaction_interval: 10m
  retention_enabled: true # Enable retention
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 7 days
  allow_structured_metadata: false
  volume_enabled: true

  # You can add more limits here as needed, e.g., ingestion_rate_mb

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h # 30 days, adjust as needed. 0s means infinite.
