[package]
name = "api"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "api"
path = "src/main.rs"

[dependencies]
types.workspace = true
utils.workspace = true
db.workspace = true
num-traits.workspace = true
