global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'loki'
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'bankai-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['bankai-api:3001']
