apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: b63075aa-d910-40b5-b142-e4ba10a5c744
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000