apiVersion: 1
datasources:
  - name: db
    uid: d091f26c-641f-4fd5-aa8f-33bca24295a5
    type: postgres
    access: proxy
    url: db:5432
    database: ${POSTGRES_DB}
    user: ${GRAFANA_DB_USER}
    secureJsonData:
      password: "${GRAFANA_DB_PASSWORD}"
    jsonData:
      postgresVersion: 1500
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400