{
 "title": "Jobs",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Sync Committee", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Created",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM jobs\nWHERE \n  (created_at AT TIME ZONE 'Europe/Berlin') >= $__timeFrom()\n  AND (created_at AT TIME ZONE 'Europe/Berlin') <= $__timeTo()\n  AND type = 'SYNC_COMMITTEE_UPDATE';"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM jobs\nWHERE \n  (created_at AT TIME ZONE 'Europe/Berlin') >= $__timeFrom()\n  AND (created_at AT TIME ZONE 'Europe/Berlin') <= $__timeTo()\n  AND job_status = 'DONE'\n  AND type = 'SYNC_COMMITTEE_UPDATE';"
    }
   ]
  },
  {
   "title": "Errored",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM jobs\nWHERE \n  (created_at AT TIME ZONE 'Europe/Berlin') >= $__timeFrom()\n  AND (created_at AT TIME ZONE 'Europe/Berlin') <= $__timeTo()\n  AND job_status = 'ERROR'\n  AND type = 'SYNC_COMMITTEE_UPDATE';"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM jobs\nWHERE \n  (created_at AT TIME ZONE 'Europe/Berlin') >= $__timeFrom()\n  AND (created_at AT TIME ZONE 'Europe/Berlin') <= $__timeTo()\n  AND job_status NOT IN ('DONE', 'ERROR')\n  AND type = 'SYNC_COMMITTEE_UPDATE';"
    }
   ]
  },
  {
   "title": "Latest Verified Committee Id",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  FLOOR(MAX(sync_committee_id) / 8192) + 1 AS committee_group\nFROM verified_sync_committee;"
    }
   ]
  },
  {
   "title": "Committee Updates",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  job_uuid                           AS \"Job UUID\",\n  job_status                         AS \"Status\",\n  slot AS \"Slot\",\n  FLOOR(slot / 8192) + 1 AS \"Committee ID\",\n  created_at,\n  AGE(updated_at, created_at)         AS \"Total Runtime\"\nFROM jobs\nWHERE (created_at AT TIME ZONE 'Europe/Berlin') >= $__timeFrom()\nAND (created_at AT TIME ZONE 'Europe/Berlin') <= $__timeTo()\nAND type = 'SYNC_COMMITTEE_UPDATE'\nORDER BY created_at DESC"
    }
   ]
  },
  { "title": "Epoch Batches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Created",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM jobs\nWHERE \n  (created_at AT TIME ZONE 'Europe/Berlin') >= $__timeFrom()\n  AND (created_at AT TIME ZONE 'Europe/Berlin') <= $__timeTo()\n  AND type = 'EPOCH_BATCH_UPDATE';"
    }
   ]
  },
  {
   "title": "Successful",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM jobs\nWHERE \n  (created_at AT TIME ZONE 'Europe/Berlin') >= $__timeFrom()\n  AND (created_at AT TIME ZONE 'Europe/Berlin') <= $__timeTo()\n  AND job_status = 'DONE'\n  AND type = 'EPOCH_BATCH_UPDATE';"
    }
   ]
  },
  {
   "title": "Errored",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM jobs\nWHERE \n  (created_at AT TIME ZONE 'Europe/Berlin') >= $__timeFrom()\n  AND (created_at AT TIME ZONE 'Europe/Berlin') <= $__timeTo()\n  AND job_status = 'ERROR'\n  AND type = 'EPOCH_BATCH_UPDATE';"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM jobs\nWHERE \n  (created_at AT TIME ZONE 'Europe/Berlin') >= $__timeFrom()\n  AND (created_at AT TIME ZONE 'Europe/Berlin') <= $__timeTo()\n  AND job_status NOT IN ('DONE', 'ERROR')\n  AND type = 'EPOCH_BATCH_UPDATE';"
    }
   ]
  },
  {
   "title": "Epoch Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(epoch_id)\nFROM verified_epoch;"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(slot)\nFROM verified_epoch;"
    }
   ]
  },
  {
   "title": "Execution Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(execution_header_height)\nFROM verified_epoch;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  job_uuid                           AS \"Job UUID\",\n  job_status                         AS \"Status\",\n  slot AS \"Slot\",\n  batch_range_begin_epoch AS \"Range Start\",\n  batch_range_end_epoch   AS \"Range End\",\n  FLOOR(batch_range_begin_epoch / 256) AS \"Committee ID\",\n  created_at,\n  AGE(updated_at, created_at)         AS \"Total Runtime\"\nFROM jobs\nWHERE (created_at AT TIME ZONE 'Europe/Berlin') >= $__timeFrom()\nAND (created_at AT TIME ZONE 'Europe/Berlin') <= $__timeTo()\nAND type = 'EPOCH_BATCH_UPDATE'\nORDER BY created_at DESC"
    }
   ]
  }
 ]
}