[package]
name = "starknet-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet.workspace = true
alloy-primitives.workspace = true
types.workspace = true