[package]
name = "beacon-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing.workspace = true
itertools.workspace = true
reqwest.workspace = true
serde_json.workspace = true
alloy-rpc-types-beacon.workspace = true
beacon-types.workspace = true
types.workspace = true